package edu.uga.cs.quizapp;

import androidx.appcompat.app.AppCompatActivity;
import android.content.Context;
import android.content.ContentValues;

import android.content.res.Resources;
import android.database.sqlite.SQLiteOpenHelper;
import android.os.AsyncTask;
import android.os.Bundle;
import android.util.Log;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;

import com.opencsv.CSVReader;

import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

public class QuizActivity extends AppCompatActivity {

    private static final String DEBUG_TAG = "Quiz Activity";

    private QuizData quizData;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Log.d( DEBUG_TAG, "Database: " + doesDatabaseExist(this, "quizapp.db"));
        quizData = new QuizData( this );
    }

    private static boolean doesDatabaseExist(Context context, String dbName) {
        File dbFile = context.getDatabasePath(dbName);
        return dbFile.exists();
    }

    // Execute the retrieval of the CSV file in an asynchronous way, without blocking the UI thread.
    // Called by DBHelper in the onCreate method bc of csv file getting needing an activity
    public void setInitialData() {
        new getIntialCSVDataTask().execute();
    }

    // This is an AsyncTask class (it extends AsyncTask) to perform grab csv file data and calls
    // quizData to insert into db.
    private class getIntialCSVDataTask extends AsyncTask<Void, Void, Void> {

        // This method will run as a background process to write into db.
        // It will be automatically invoked by Android, when we call the execute method
        // in the onCreateMethod
        @Override
        protected Void doInBackground(Void... voids) {
            Log.d( DEBUG_TAG, "Here in create: " );
            try {
                Resources res = getResources();
                InputStream in_s = res.openRawResource( R.raw.state_capitals );
//                    String file = "src/main/res/raw/state_capitals.csv";
//                    InputStream in_s = this.getClass().getClassLoader().getResourceAsStream(file);

                // read the CSV data
                CSVReader reader = new CSVReader(new InputStreamReader(in_s));
                String[] nextLine;


                while ((nextLine = reader.readNext()) != null) {
                    System.out.println("State : " + nextLine[0]);
                    System.out.println("Capital : " + nextLine[1]);
                    System.out.println("Second city : " + nextLine[2]);
                    System.out.println("Third city : " + nextLine[3]);
                    System.out.println("==========================");
                    ContentValues values = new ContentValues();
                    values.put(QuizDBHelper.QUIZQUESTIONS_COLUMN_STATE, nextLine[0]);
                    values.put(QuizDBHelper.QUIZQUESTIONS_COLUMN_CAPITAL, nextLine[1]);
                    values.put(QuizDBHelper.QUIZQUESTIONS_COLUMN_CITY1, nextLine[2]);
                    values.put(QuizDBHelper.QUIZQUESTIONS_COLUMN_CITY2, nextLine[3]);

                    // Insert the new row into the database table;
                    // The id (primary key) is automatically generated by the database system
                    // and returned as from the insert method call.
                    quizData.insertQuestion(values);
                }

                reader.close();

            } catch(Exception e) {
                Log.e(DEBUG_TAG, e.toString());
            }
            Log.d( DEBUG_TAG, "getIntialCSVDataTask: quiz questions retrieved: ");
            return null;
        }
    }
}
